version: '3'

services:
  api_fast:

    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    
    ports:
      - "8000:8000"

    volumes:
      - "/home/phytter/Documents/Projects/recognition-server/src/:/app"
