FROM tensorflow/tensorflow


RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

RUN mkdir app

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app/

RUN apt-get update --fix-missing

RUN apt-get install ffmpeg libjpeg-dev libsm6 libxext6  -y

RUN pip install -I pillow

RUN pip install -r requirements.txt

RUN ls

ENTRYPOINT [ "python", "server.py" ]
